#!/bin/bash
# catalog.sh — Scan sources/ and build a lightweight catalog of all documents
# No deep ingestion — just metadata from filenames, file size, format.
# Creates/updates wiki/catalog.md and marks ingestion status.
# Optimized for large collections (1000+ files) — bulk operations, minimal subprocesses.
#
# Usage: catalog.sh [--format pdf|html|epub|markdown] [--quick]
# Env: WIKI_PATH, WIKI_SOURCES_PATH

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Parse args ───────────────────────────────────────────────────────────────

FORMAT_FILTER=""
QUICK=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --format)
            FORMAT_FILTER="$2"
            shift 2
            ;;
        --quick)
            QUICK=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# ── Setup ────────────────────────────────────────────────────────────────────

CATALOG_FILE="$WIKI_PATH/catalog.md"
INGESTED_FILE="$WIKI_PATH/.ingested"
LOG_FILE="$WIKI_PATH/log.md"

TMPDIR_WORK=$(mktemp -d)
trap 'rm -rf "$TMPDIR_WORK"' EXIT

# Build combined ingested list
INGESTED_TMP="$TMPDIR_WORK/ingested"
touch "$INGESTED_TMP"

[ -f "$INGESTED_FILE" ] && cat "$INGESTED_FILE" >> "$INGESTED_TMP"

if [ -f "$LOG_FILE" ]; then
    awk -F'|' '$3 ~ /ingest/ { gsub(/^ +| +$/, "", $4); if ($4 != "") print $4 }' "$LOG_FILE" >> "$INGESTED_TMP"
fi

# Sort and deduplicate for fast lookup
sort -u "$INGESTED_TMP" -o "$INGESTED_TMP"

# ── Quick mode: counts only, no catalog.md ───────────────────────────────────

if [ "$QUICK" = true ]; then
    FORMAT_JSON="{}"
    TOTAL=0
    for subdir in "$WIKI_SOURCES_PATH"/*/; do
        [ -d "$subdir" ] || continue
        FORMAT="$(basename "$subdir")"
        [ -n "$FORMAT_FILTER" ] && [ "$FORMAT" != "$FORMAT_FILTER" ] && continue
        COUNT=$(find "$subdir" -maxdepth 1 -type f | wc -l | tr -d ' ')
        TOTAL=$((TOTAL + COUNT))
        FORMAT_JSON=$(echo "$FORMAT_JSON" | jq --arg f "$FORMAT" --argjson c "$COUNT" '.[$f] = $c')
    done

    INGESTED_COUNT=$(wc -l < "$INGESTED_TMP" | tr -d ' ')
    PENDING=$((TOTAL - INGESTED_COUNT))
    [ "$PENDING" -lt 0 ] && PENDING=0

    jq -n \
        --arg action "catalog" \
        --argjson total "$TOTAL" \
        --argjson ingested "$INGESTED_COUNT" \
        --argjson pending "$PENDING" \
        --argjson by_format "$FORMAT_JSON" \
        '{
            action: $action,
            total: $total,
            ingested: $ingested,
            pending: $pending,
            by_format: $by_format,
            message: ("Quick catalog: " + ($total | tostring) + " documents (" + ($ingested | tostring) + " ingested, " + ($pending | tostring) + " pending).")
        }'
    exit 0
fi

# ── Full catalog: build catalog.md ───────────────────────────────────────────

# Use find + stat in bulk, pipe through awk for all processing
# Output: format\tsize\tfilename\tstatus lines
ENTRIES_TMP="$TMPDIR_WORK/entries"
FORMAT_TMP="$TMPDIR_WORK/formats"

TOTAL=0
TOTAL_INGESTED=0
TOTAL_PENDING=0

for subdir in "$WIKI_SOURCES_PATH"/*/; do
    [ -d "$subdir" ] || continue
    FORMAT="$(basename "$subdir")"
    [ -n "$FORMAT_FILTER" ] && [ "$FORMAT" != "$FORMAT_FILTER" ] && continue

    # Get all files with sizes in one find call (macOS stat format)
    find "$subdir" -maxdepth 1 -type f -exec stat -f '%z %N' {} \; 2>/dev/null | \
    while IFS= read -r line; do
        SIZE="${line%% *}"
        FILEPATH="${line#* }"
        FILENAME="$(basename "$FILEPATH")"

        # Title: remove extension, replace - and _ with space
        TITLE="${FILENAME%.*}"
        TITLE=$(echo "$TITLE" | tr '-_' '  ')

        # Human size (inline, no subprocess)
        if [ "$SIZE" -ge 1048576 ]; then
            HSIZE="$((SIZE / 1048576))MB"
        elif [ "$SIZE" -ge 1024 ]; then
            HSIZE="$((SIZE / 1024))KB"
        else
            HSIZE="${SIZE}B"
        fi

        # Ingestion status via sorted file lookup
        if grep -qxF "$FILENAME" "$INGESTED_TMP" 2>/dev/null; then
            STATUS="ingested"
        else
            STATUS="pending"
        fi

        echo "| $TITLE | $FORMAT | $HSIZE | $STATUS | \`$FILENAME\` |"
    done
done > "$ENTRIES_TMP"

# Count totals from the entries file (fast)
TOTAL=$(wc -l < "$ENTRIES_TMP" | tr -d ' ')
TOTAL_INGESTED=$(grep -c '| ingested |' "$ENTRIES_TMP" 2>/dev/null || echo "0")
TOTAL_PENDING=$((TOTAL - TOTAL_INGESTED))

# Format counts
for subdir in "$WIKI_SOURCES_PATH"/*/; do
    [ -d "$subdir" ] || continue
    FORMAT="$(basename "$subdir")"
    [ -n "$FORMAT_FILTER" ] && [ "$FORMAT" != "$FORMAT_FILTER" ] && continue
    COUNT=$(grep -c "| $FORMAT |" "$ENTRIES_TMP" 2>/dev/null || echo "0")
    [ "$COUNT" -gt 0 ] && echo "$FORMAT $COUNT"
done > "$FORMAT_TMP"

# ── Write catalog.md ─────────────────────────────────────────────────────────

{
    echo "# Source Catalog"
    echo ""
    echo "Auto-generated by \`/wiki catalog\`. Total: **$TOTAL** documents (**$TOTAL_INGESTED** ingested, **$TOTAL_PENDING** pending)."
    echo ""
    echo "## Summary"
    echo ""
    echo "| Format | Count |"
    echo "|--------|-------|"
    while read -r fmt count; do
        echo "| $fmt | $count |"
    done < "$FORMAT_TMP"
    echo ""
    echo "## All Sources"
    echo ""
    echo "| Title | Format | Size | Status | Filename |"
    echo "|-------|--------|------|--------|----------|"
    sort -t'|' -k2,2 -k1,1 "$ENTRIES_TMP"
    echo ""
    echo "---"
    echo "*Last updated: $(date +%Y-%m-%d)*"
} > "$CATALOG_FILE"

# ── Output JSON summary ─────────────────────────────────────────────────────

FORMAT_JSON="{}"
while read -r fmt count; do
    FORMAT_JSON=$(echo "$FORMAT_JSON" | jq --arg f "$fmt" --argjson c "$count" '.[$f] = $c')
done < "$FORMAT_TMP"

jq -n \
    --arg action "catalog" \
    --argjson total "$TOTAL" \
    --argjson ingested "$TOTAL_INGESTED" \
    --argjson pending "$TOTAL_PENDING" \
    --argjson by_format "$FORMAT_JSON" \
    --arg catalog_file "$CATALOG_FILE" \
    '{
        action: $action,
        total: $total,
        ingested: $ingested,
        pending: $pending,
        by_format: $by_format,
        catalog_file: $catalog_file,
        message: ("Catalog written to catalog.md. " + ($total | tostring) + " documents found (" + ($ingested | tostring) + " ingested, " + ($pending | tostring) + " pending).")
    }'
