#!/bin/bash
# catalog.sh — Scan sources/ and build a lightweight catalog of all documents
# No deep ingestion — just metadata from filenames, file size, format.
# Creates/updates wiki/catalog.md and marks ingestion status.
#
# Usage: catalog.sh [--format pdf|html|epub|markdown] [--refresh]
# Env: WIKI_PATH, WIKI_SOURCES_PATH

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Parse args ───────────────────────────────────────────────────────────────

FORMAT_FILTER=""
REFRESH=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --format)
            FORMAT_FILTER="$2"
            shift 2
            ;;
        --refresh)
            REFRESH=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# ── Scan sources ─────────────────────────────────────────────────────────────

CATALOG_FILE="$WIKI_PATH/catalog.md"
INGESTED_FILE="$WIKI_PATH/.ingested"
LOG_FILE="$WIKI_PATH/log.md"

# Load already-ingested files
declare -A INGESTED_MAP
if [ -f "$INGESTED_FILE" ]; then
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        INGESTED_MAP["$line"]=1
    done < "$INGESTED_FILE"
fi

# Also check log.md for ingested files
if [ -f "$LOG_FILE" ]; then
    while IFS='|' read -r _ _ op details _ _; do
        op=$(echo "$op" | xargs 2>/dev/null || true)
        [ "$op" = "ingest" ] || continue
        details=$(echo "$details" | xargs 2>/dev/null || true)
        [ -n "$details" ] && INGESTED_MAP["$details"]=1
    done < "$LOG_FILE"
fi

# Title from filename: kebab-case → Title Case
filename_to_title() {
    local name="$1"
    # Remove extension
    name="${name%.*}"
    # Replace hyphens and underscores with spaces
    name=$(echo "$name" | tr '-_' '  ')
    # Title case (capitalize first letter of each word)
    echo "$name" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

# Human-readable file size
human_size() {
    local bytes="$1"
    if [ "$bytes" -ge 1048576 ]; then
        echo "$((bytes / 1048576))MB"
    elif [ "$bytes" -ge 1024 ]; then
        echo "$((bytes / 1024))KB"
    else
        echo "${bytes}B"
    fi
}

# ── Build catalog ────────────────────────────────────────────────────────────

TOTAL=0
TOTAL_INGESTED=0
TOTAL_PENDING=0
declare -A FORMAT_COUNTS

# Temp file for catalog entries
ENTRIES_TMP=$(mktemp)
trap 'rm -f "$ENTRIES_TMP"' EXIT

for subdir in "$WIKI_SOURCES_PATH"/*/; do
    [ -d "$subdir" ] || continue
    FORMAT="$(basename "$subdir")"

    # Apply format filter
    if [ -n "$FORMAT_FILTER" ] && [ "$FORMAT" != "$FORMAT_FILTER" ]; then
        continue
    fi

    for file in "$subdir"/*; do
        [ -f "$file" ] || continue
        FILENAME="$(basename "$file")"
        TITLE=$(filename_to_title "$FILENAME")
        SIZE=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo "0")
        HUMAN_SIZE=$(human_size "$SIZE")
        MOD_DATE=$(stat -f%Sm -t%Y-%m-%d "$file" 2>/dev/null || stat -c%y "$file" 2>/dev/null | cut -d' ' -f1 || echo "unknown")

        # Check ingestion status
        STATUS="pending"
        if [ -n "${INGESTED_MAP[$FILENAME]:-}" ]; then
            STATUS="ingested"
            TOTAL_INGESTED=$((TOTAL_INGESTED + 1))
        else
            TOTAL_PENDING=$((TOTAL_PENDING + 1))
        fi

        TOTAL=$((TOTAL + 1))
        FORMAT_COUNTS[$FORMAT]=$(( ${FORMAT_COUNTS[$FORMAT]:-0} + 1 ))

        echo "| $TITLE | $FORMAT | $HUMAN_SIZE | $STATUS | \`$FILENAME\` |" >> "$ENTRIES_TMP"
    done
done

# ── Write catalog.md ─────────────────────────────────────────────────────────

{
    echo "# Source Catalog"
    echo ""
    echo "Auto-generated by \`/wiki catalog\`. Total: **$TOTAL** documents (**$TOTAL_INGESTED** ingested, **$TOTAL_PENDING** pending)."
    echo ""

    # Summary by format
    echo "## Summary"
    echo ""
    echo "| Format | Count |"
    echo "|--------|-------|"
    for fmt in "${!FORMAT_COUNTS[@]}"; do
        echo "| $fmt | ${FORMAT_COUNTS[$fmt]} |"
    done
    echo ""

    # Full table
    echo "## All Sources"
    echo ""
    echo "| Title | Format | Size | Status | Filename |"
    echo "|-------|--------|------|--------|----------|"
    sort -t'|' -k2,2 -k1,1 "$ENTRIES_TMP"
    echo ""
    echo "---"
    echo "*Last updated: $(date +%Y-%m-%d)*"
} > "$CATALOG_FILE"

# ── Output JSON summary ─────────────────────────────────────────────────────

FORMAT_JSON="{}"
for fmt in "${!FORMAT_COUNTS[@]}"; do
    FORMAT_JSON=$(echo "$FORMAT_JSON" | jq --arg f "$fmt" --argjson c "${FORMAT_COUNTS[$fmt]}" '.[$f] = $c')
done

jq -n \
    --arg action "catalog" \
    --argjson total "$TOTAL" \
    --argjson ingested "$TOTAL_INGESTED" \
    --argjson pending "$TOTAL_PENDING" \
    --argjson by_format "$FORMAT_JSON" \
    --arg catalog_file "$CATALOG_FILE" \
    '{
        action: $action,
        total: $total,
        ingested: $ingested,
        pending: $pending,
        by_format: $by_format,
        catalog_file: $catalog_file,
        message: ("Catalog written to catalog.md. " + ($total | tostring) + " documents found (" + ($ingested | tostring) + " ingested, " + ($pending | tostring) + " pending).")
    }'
